import StoreProvider from '@/_StoreProvider';
import {Inter} from 'next/font/google';
import Navbar from '@/_components/Navbar';
import Footer from '@/_components/Footer';
import '@/globals.css';

const inter = Inter({subsets: ['latin']});

export const metadata = {
  title: 'Test Zen Commerce',
  description: 'Generated by create next app',
};

export default function RootLayout({children}) {
  return (
    <StoreProvider>
      <html lang="en">
        <body className={inter.className}>
          <section className="w-full relative min-w-[360px] gap-y-6 flex flex-col min-h-dvh text-slate-700">
            <Navbar />
            <main className="mx-auto gap-y-4 flex flex-col w-full min-h-[calc(100dvh_-_(56px_+_24px_+_1px)_-_(48px_+_24px_+_1px))] max-w-[calc(1200px_+_(16px_*_2))] px-4">
              {children}
            </main>
            <Footer />
          </section>
        </body>
      </html>
    </StoreProvider>
  );
}
